global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter_local'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'node_exporter_remote'
    static_configs:
      - targets: ['<IP_MACHINE2>:9100']  
